language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - python setup.py build_ext --inplace
script:
  - pytest --cov=./
after_success:
  - bash < (curl -s https://codecov.io/bash)
